### ISSUE TITLE
Landing Page development

### ISSUE THREAD

**Issue by 97Clinton** [zuri-training/Fetch_Metadata_Team82#1]
The design for the **landing page** is all set, so now start working on developing the **landing page.******

**Comment by KosiNina** [comment]
I am just testing to know how to navigate.

**Comment by danielpeace7** [comment]
Landing page completed can be viewed at:

Live Page: [(https://danielpeace7.github.io/Metadata-Landing-Page/)]
Code: https://github.com/danielpeace7/Metadata-Landing-Page

![image](https://user-images.githubusercontent.com/102909682/183628402-f454bbf3-591e-4865-b713-ab9ac5e988d0.png)
