### ISSUE TITLE
CREATE  LOW AND HIGH FIDELITY DESIGNS FOR THE HERO SECTION AND AUTHENTICATION PAGES

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#10]
Kindly submit the figma link and screenshot of what you did. Thanks

**Comment by appipiah** [comment]
LINKS TO THE HIGH-FIDELITY DESIGNS FOR THE PAGES I WORKED ON:

Hero section for the landing page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=242%3A271

Login Page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=254%3A499

Sign up page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=254%3A449

**Comment by appipiah** [comment]
LINKS TO THE LOW-FIDELITY DESIGNS I WORKED ON:

Hero section for the landing page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A2922

Login Page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A3134

Sign up page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A3080

**Comment by appipiah** [comment]
![hero_section_desktop_view_hi-fi](https://user-images.githubusercontent.com/42087529/183767026-e105c692-5644-493d-843d-d53746faf031.png)
![hero_section_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183767163-3a9108ae-67d2-4e26-a235-5e07dd033430.png)
![login_page_desktop_view_high-fi](https://user-images.githubusercontent.com/42087529/183767182-03d1aeec-cccb-4d5f-8c3b-01ebdb0e4974.png)
![login_page_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183767213-12cb6e36-20e8-43fc-b7ee-cce2a2d9f920.png)
![signup_page_desktop_view_high-fi](https://user-images.githubusercontent.com/42087529/183767238-5c80750d-373f-4d34-89a8-ec6c7d7c1c20.png)
![signup_page_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183767251-ce242ee9-fc0c-4d28-a37d-b1797b0597b2.png)

**Comment by danielpeace7** [comment]
Well done
