### ISSUE TITLE
IMPROVE FINAL DESIGN FOR THE WEB AND MOBILE SCREENS OF THE LANDING PAGE AND AUTHENTICATION PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#12]
Kindly submit the figma link and screenshot of what you did. Thanks

**Comment by appipiah** [comment]
LINKS TO THE HIGH-FIDELITY DESIGNS FOR THE PAGES I WORKED ON:

Hero section for the landing page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=242%3A271


Login Page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=254%3A499


Sign up page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=254%3A449


Landing page - Mobile view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=732%3A773


Login page - Mobile view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1275%3A728


Sign up page - Mobile view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=774%3A722

**Comment by appipiah** [comment]
LINKS TO THE LOW-FIDELITY DESIGNS I WORKED ON:

Hero section for the landing page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A2922

Login Page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A3134

Sign up page - Desktop view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A3080

Landing page - Mobile view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A2556

Login page - Mobile view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A3176

Sign up page - Mobile view
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A1566

**Comment by appipiah** [comment]
SCREENSHOTS OF THE PAGES I WORKED ON:

![hero_section_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183727441-079796c7-4751-4879-b7fc-02be70728676.png)
![landing_page_mobile_view_high-fi](https://user-images.githubusercontent.com/42087529/183727506-8a839de9-707b-4d63-9ddc-7739d009eb57.png)
![landing_page_mobile_view_low-fi](https://user-images.githubusercontent.com/42087529/183727528-55dcaf03-8a99-42b6-b372-cf17f83b6d70.png)
![login_page_desktop_view_high-fi](https://user-images.githubusercontent.com/42087529/183727591-561641a9-48c1-4943-9ae7-bf71341c503d.png)
![login_page_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183727616-3477c9a5-6458-4c6a-a461-0eb8559c47c9.png)
![login_page_mobile_view_high-fi](https://user-images.githubusercontent.com/42087529/183727633-cd341b1b-4b67-489d-a1a4-6791d4dd4641.png)
![login_page_mobile_view_low-fi](https://user-images.githubusercontent.com/42087529/183727652-92e4ae51-e39d-4984-a41d-3d0e080f00c3.png)
![signup_page_desktop_view_high-fi](https://user-images.githubusercontent.com/42087529/183727701-ab09db30-4caf-45f9-bcf8-0776068e6325.png)
![signup_page_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183727741-f66a5e94-088c-4983-9293-7cc77a5ce5d1.png)
![signup_page_mobile_view_high-fi](https://user-images.githubusercontent.com/42087529/183727775-18c48452-d61d-4d5e-9f69-0d238564cf0e.png)
![Signup_page_mobile_view_low-fi](https://user-images.githubusercontent.com/42087529/183727806-fe616168-448d-40f3-9c3a-26e607762d64.png)

**Comment by danielpeace7** [comment]
Well done

**Comment by danielpeace7** [comment]
Just noticed you have still have an open issue, and some of the links you pasted here are for the open issue. Kindly edit your comments and move the necessary links to the open issue so I can close both. Thanks

**Comment by appipiah** [comment]
SCREENSHOTS OF THE PAGES I WORKED ON:

![hero_section_desktop_view_hi-fi](https://user-images.githubusercontent.com/42087529/183732869-aba9d181-d77c-4ff0-a4c0-da8d0d00d225.png)
![hero_section_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183732916-75986e3a-a9b8-4cac-a140-2175ca3fb31b.png)
![landing_page_mobile_view_high-fi](https://user-images.githubusercontent.com/42087529/183732919-25758de0-17e7-47a7-81c5-37daa9f582ea.png)
![landing_page_mobile_view_low-fi](https://user-images.githubusercontent.com/42087529/183732931-376cb9fe-46d3-46a5-9630-e99d91f1ca8a.png)
![login_page_desktop_view_high-fi](https://user-images.githubusercontent.com/42087529/183732940-e13186dd-5216-46af-b88d-5370f5aa3bb3.png)
![login_page_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183732948-1c053f99-37f3-4147-89e9-ca73031c11ce.png)
![login_page_mobile_view_high-fi](https://user-images.githubusercontent.com/42087529/183732955-62d7e41c-3595-425d-9530-70737016edb1.png)
![login_page_mobile_view_low-fi](https://user-images.githubusercontent.com/42087529/183732961-c1d3249f-c857-4c48-b12d-acbb4e53fab1.png)
![signup_page_desktop_view_high-fi](https://user-images.githubusercontent.com/42087529/183732966-80fcb788-5835-4d85-9318-cd82faa2fcc5.png)
![signup_page_desktop_view_low-fi](https://user-images.githubusercontent.com/42087529/183732970-1333d311-ea49-4530-957b-4d02e1fdf873.png)
![signup_page_mobile_view_high-fi](https://user-images.githubusercontent.com/42087529/183732978-7bfcc088-7ee8-4c20-90e3-b95e5e7969c9.png)
![Signup_page_mobile_view_low-fi](https://user-images.githubusercontent.com/42087529/183732984-776f82f0-63cf-4e18-a1c3-2b4abdcd178a.png)

**Comment by danielpeace7** [comment]
Well done
