### ISSUE TITLE
USER FILE UPLOAD AND DOWNLOAD

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#18]
Kindly submit the link to the code or screenshot of the output. Thanks

**Comment by FitsumMehari** [comment]
https://github.com/zuri-training/Fetch_Metadata_Team82/tree/master/api/FrontEnd/metadata%20page

added AJAX call to api for generation of metadata and file upload. Also added an AJAX call for downloading of files

**Comment by danielpeace7** [comment]
Well done
