### ISSUE TITLE
DEVELOP SKETCHES AND WIREFRAME FOR THE WEBSITE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#22]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Oladejo-ayomide** [comment]
https://www.figma.com/file/CmEnpH5IWdILqmnhdUrBeQ/METADATA-D-(Copy)?node-id=16%3A17
![sketches](https://user-images.githubusercontent.com/65877739/183756042-4df8ec72-4f18-4e05-8c88-40323800fbd8.PNG)

**Comment by danielpeace7** [comment]
Well done
