### ISSUE TITLE
DESIGN MOBILE VIEW LOFI FOR THE LANDING PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#23]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Oladejo-ayomide** [comment]
https://www.figma.com/file/CmEnpH5IWdILqmnhdUrBeQ/METADATA-D-(Copy)?node-id=9%3A2
![lofi landing page](https://user-images.githubusercontent.com/65877739/183757029-a5109760-2784-47fe-8d54-dab7c1df4595.PNG)

**Comment by danielpeace7** [comment]
Well done
