### ISSUE TITLE
IMPROVE THE DESIGN FOR THE WEB AND MOBILE VIEW OF THE SAVED PAGE, FINAL PAGE, AND METADATA INFORMATION PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#24]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Oladejo-ayomide** [comment]
https://www.figma.com/file/CmEnpH5IWdILqmnhdUrBeQ/METADATA-D-(Copy)?node-id=0%3A1
![metadata page mobile view](https://user-images.githubusercontent.com/65877739/183757581-7ee69764-fa10-479a-a5a8-a14d8ed92932.PNG)
![metadata page web view](https://user-images.githubusercontent.com/65877739/183757624-91f3ecc6-cfb5-475b-a71a-2e7f57e5cc71.PNG)

**Comment by danielpeace7** [comment]
Well done
