### ISSUE TITLE
DEVELOP PROTOTYPE FOR THE WEB VIEW OF THE DESIGN PROJECT

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#25]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Oladejo-ayomide** [comment]
https://www.figma.com/file/CmEnpH5IWdILqmnhdUrBeQ/METADATA-D-(Copy)?node-id=0%3A1
![prototype](https://user-images.githubusercontent.com/65877739/183758052-fb63fb9f-9f0b-4e84-b9cf-49352301f813.PNG)

**Comment by danielpeace7** [comment]
Well done
