### ISSUE TITLE
IMPROVE THE PROTOTYPE OF THE MOBILE VIEW AND FINAL DESIGNS OF THE PROJECT

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#26]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Oladejo-ayomide** [comment]
https://www.figma.com/file/CmEnpH5IWdILqmnhdUrBeQ/METADATA-D-(Copy)?node-id=0%3A1
![Prototype mobile view](https://user-images.githubusercontent.com/65877739/183758279-59651cca-27cb-4135-b24f-5afd5de42c00.PNG)

**Comment by danielpeace7** [comment]
Well done
