### ISSUE TITLE
DESIGN MOBILE VIEW LOFI FOR FINAL PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#27]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by firstladyexcel** [comment]
Final page and manage account pop-up overlay
![Screenshot (35)](https://user-images.githubusercontent.com/105558869/183776333-f7994eaa-bb28-46c4-bc02-1bde712680f4.png)

https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1366%3A2080

**Comment by danielpeace7** [comment]
Well done

**Comment by ayoade007** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1366%3A2080
<img width="1680" alt="Screenshot 2022-08-10 at 6 20 56 AM" src="https://user-images.githubusercontent.com/40247277/183821929-9e1cfdf5-cb22-4a42-bbec-092c0bddf80d.png">
