### ISSUE TITLE
BACKEND DEVELOPERS

### ISSUE THREAD

**Issue by FitsumMehari** [zuri-training/Fetch_Metadata_Team82#3]
**Welcome everyone to the backend.**
###Let's work on these for now.
@trapmoneyrai ON ROUTES FOR DOWNLOADING AND SHARING OF METADATA AND FILES TO OTHER SITES 
@Greyshaws ON UPLOADING OF FILES FROM THE SERVER TO OTHER FILE SHARING SITES LIKE https://cloudinary.com/
@chukwujike ON USER REVIEW SECTION
@FitsumMehari ON GENERATION OF METADATA AND USER AUTHORIZATION AND AUTHENTICATION.

***IF WE HAVE TO CHANGE DATABASE WE WILL HAVE TO ASSIGN NEW TASKS LATER. BUT FOR NOW LET'S FINISH THESE BY TUESDAY.***
__THANK YOU! __

**Comment by trapmoneyrai** [comment]
Seen. If I run into any issues - I will ask for assistance where possible

**Comment by FitsumMehari** [comment]
I have finished my tasks for now. Once you guys finish we will make the necessary updates and give the documentation to the frontend developers.

**Comment by FitsumMehari** [comment]
@Greyshaws  did her best, but for some reason she had a problem with creating an account on cloudinary, so I used my own account and with small changes to the code, it now successfully uploads files to the cloudinary site.
Thank you @Greyshaws  for your effort.

**Comment by FitsumMehari** [comment]
route for getting all files is now working

**Comment by FitsumMehari** [comment]
All is done except the social media sharing, @trapmoneyrai  we are waiting.

**Comment by trapmoneyrai** [comment]
I'm waiting for the front-end code so that I can link their share button to my event listeners

**Comment by FitsumMehari** [comment]
great job

**Comment by KosiNina** [comment]
Well done guys

**Comment by chukwujike** [comment]
Go team 82

**Comment by FitsumMehari** [comment]
register, login, upload file, generate metadata, download file work. And also I've made some changes to the generate meta data page with some styling and js

**Comment by FitsumMehari** [comment]
register, login, upload file, get metadata, download file, share, change password, logout, get all files work. We need whoever works on the landing page to make the FAQ cards to be functional.
github Link: https://github.com/zuri-training/Fetch_Metadata_Team82/tree/master
