### ISSUE TITLE
DESIGN FINAL PAGE AND POPUP

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#30]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by KosiNina** [comment]
[https://www.figma.com/file/WPk4GEqy2catVJdd9gPTdV/Untitled?node-id=38%3A2458](url)

**Comment by KosiNina** [comment]
https://www.figma.com/file/WPk4GEqy2catVJdd9gPTdV/Untitled?node-id=38%3A2458

**Comment by KosiNina** [comment]
Did the high fi for the final page

**Comment by danielpeace7** [comment]
Screenshot of the design?

**Comment by KosiNina** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A993
Done

**Comment by KosiNina** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1338%3A777
Done

**Comment by danielpeace7** [comment]
Submit the screenshot of the pages too

**Comment by KosiNina** [comment]
![Screenshot 2022-08-09 185346](https://user-images.githubusercontent.com/61625651/183819384-ff557b09-bd66-42a5-bf00-a30270242c7e.png)

**Comment by KosiNina** [comment]
Done

**Comment by danielpeace7** [comment]
Well done
