### ISSUE TITLE
DESIGN LOFI AND HIFI FOR THE SAVED PAGES (WEB AND MOBILE VIEW)

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#31]

**Comment by KosiNina** [comment]
[https://www.figma.com/file/WPk4GEqy2catVJdd9gPTdV/Untitled?node-id=38%3A2458](url)

**Comment by KosiNina** [comment]
https://www.figma.com/file/WPk4GEqy2catVJdd9gPTdV/Untitled?node-id=38%3A2458

**Comment by KosiNina** [comment]
Did the lofi and high fi for saved pages

**Comment by danielpeace7** [comment]
Screenshot of the design?

**Comment by KosiNina** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=665%3A1430
Done.

**Comment by KosiNina** [comment]
![Screenshot 2022-08-09 182911](https://user-images.githubusercontent.com/61625651/183819282-92df02ba-d410-4784-aae9-3cb05fcb0548.png)

**Comment by KosiNina** [comment]
![Screenshot 2022-08-09 184916](https://user-images.githubusercontent.com/61625651/183819323-4f767b24-452b-4c1c-95fb-c5b9c409f195.png)

**Comment by KosiNina** [comment]
Done

**Comment by danielpeace7** [comment]
Well done
