### ISSUE TITLE
DESIGN MOBILE AND WEB VIEW FOR METADATA INFORMATION PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#32]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by ladytestimony** [comment]
![IMG-20220809-WA0054](https://user-images.githubusercontent.com/105352906/183702834-22036a1f-542b-4a7f-a85c-a8b9e3911666.jpg)

Web View

**Comment by ladytestimony** [comment]
![IMG-20220809-WA0055](https://user-images.githubusercontent.com/105352906/183703062-025403e8-b661-463b-ba76-be2c0a180469.jpg)

[https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1366%3A805](url)

Mobile view

**Comment by danielpeace7** [comment]
Well done
