### ISSUE TITLE
DESIGN LOFI FOR SIGN UP/LOGIN PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#33]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Amahkah** [comment]
Link to Signup and Login page (Web view)
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A3080
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1332%3A3134

**Comment by danielpeace7** [comment]
Screenshot?

**Comment by danielpeace7** [comment]
Well done
