### ISSUE TITLE
IMPROVE LANDING PAGE DESIGN

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#34]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Amahkah** [comment]
Link to Landing page design
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=242%3A271

**Comment by danielpeace7** [comment]
Screenshot of the design?

**Comment by danielpeace7** [comment]
Well done

**Comment by Crystannson** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=242%3A271
![Artboard 1](https://user-images.githubusercontent.com/53399623/183860660-40c6adc8-5016-4d06-b05a-35d3ed434a91.png)

**Comment by Crystannson** [comment]
Done
