### ISSUE TITLE
DESIGN LOFI FOR MANAGE ACCOUNT POPUP

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#35]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by ayoade007** [comment]
https://www.figma.com/file/kFSVTgNuyuZ6XNuXmrImMD/Untitled?node-id=1420%3A902
<img width="1680" alt="Screenshot 2022-08-09 at 4 51 15 PM" src="https://user-images.githubusercontent.com/40247277/183699389-98d0f007-1fae-4ec5-8e40-52637093ef67.png">

**Comment by danielpeace7** [comment]
Well done
