### ISSUE TITLE
TEAM'S FIRST PRESENTATION

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#36]
Kindly note that you'd be presenting for the team, please submit the link to the presentation video and slides. Thanks

**Comment by Thefrocreative** [comment]
Noted.

**Comment by Thefrocreative** [comment]
The link to the slides: https://www.figma.com/file/6wQOaNlEJ7PsiLucwWTSmp/Team-82-Project-Presentation
