### ISSUE TITLE
MAKE CHANGES TO THE FINAL DESIGN

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#37]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Thefrocreative** [comment]
The link: https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=0%3A1

![image](https://user-images.githubusercontent.com/105223401/183763606-efd28ed3-c7ad-4cde-90e0-e4cea1a92e58.png)

**Comment by danielpeace7** [comment]
Well done
