### ISSUE TITLE
DESIGN MOBILE VIEW FOR AUTHENTICATION PAGES

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#38]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by Osayomwanbo** [comment]
Done

**Comment by danielpeace7** [comment]
Boss read the description of this issue

**Comment by Osayomwanbo** [comment]
Authentication pages
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=774%3A722
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=1275%3A728

Screenshot
![Screenshot (97)](https://user-images.githubusercontent.com/105309579/183782354-a81fa3e9-7271-4d94-bfdb-790aeaf391bf.png)

**Comment by Osayomwanbo** [comment]
Done

**Comment by danielpeace7** [comment]
Well done
