### ISSUE TITLE
DESIGN THE MOBILE VIEW HIFI FOR THE LANDING PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#39]
Kindly submit the figma link and screenshot of the output. Thanks

**Comment by appipiah** [comment]
Link to the High-fi design of the landing page, mobile view:
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=732%3A773

**Comment by appipiah** [comment]
![landing_page_mobile_view_high-fi](https://user-images.githubusercontent.com/42087529/183762274-d8ef525b-31df-4775-89cd-fd2f11cd7861.png)

-Screenshot of the design

**Comment by danielpeace7** [comment]
Well done
