### ISSUE TITLE
DESIGN ROUTE AND DATA SCHEMA FOR USER REVIEWS

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#40]
Kindly submit the link to the design and screenshot of the output. Thanks

**Comment by chukwujike** [comment]
https://github.com/chukwujike/User_review

**Comment by chukwujike** [comment]
Link to the database schema.
https://drive.google.com/file/d/1GtuaFKwdVvIUjQ5EKAnmXgYd1IsVrV2X/view?usp=sharing

**Comment by danielpeace7** [comment]
Well done
