### ISSUE TITLE
CREATE ROUTES FOR DOWNLOADING AND SHARING OF METADATA FILES TO OTHER USERS/SITES

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#41]
Kindly submit the link to the code and screenshot of the output (if any). Thanks

**Comment by trapmoneyrai** [comment]
https://github.com/Prissy-Ama/Fetch_Metadata

I can't find the work in the team folder but this is my effective contribution in the form of pull requests
