### ISSUE TITLE
CREATE RESEARCH DOCUMENTS

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#42]
Kindly attach the link to the research documents and screenshot of output (if any). Thanks

**Comment by Osayomwanbo** [comment]
Done

**Comment by danielpeace7** [comment]
Submit the link to the research document and the screenshot

**Comment by Osayomwanbo** [comment]
Research documents 
https://docs.google.com/document/d/1T1cII0G8fGpGwWi1ovo-MB_FKBJRfrlWzvHdSxUNtCQ/edit?usp=drivesdk

Screenshot 
![Screenshot_20220809-235845](https://user-images.githubusercontent.com/105309579/183776538-1d6e56c5-bc5e-43cd-ab8c-66c7e1c35664.png)
![Screenshot_20220809-235859](https://user-images.githubusercontent.com/105309579/183776585-a8f0567e-392e-49eb-9591-b8f5ee8b9c79.png)
![Screenshot_20220809-235921](https://user-images.githubusercontent.com/105309579/183776608-0523b3c6-96e9-4419-9942-97cfc7ab1581.png)
![Screenshot_20220809-235943](https://user-images.githubusercontent.com/105309579/183776680-3c987b7d-1a54-48e3-a8e1-8d70aedc0255.png)

**Comment by Osayomwanbo** [comment]
![Screenshot_20220809-235943](https://user-images.githubusercontent.com/105309579/183776792-5307fe20-cca1-426e-891b-9cbaa5195583.png)
![Screenshot_20220809-235949](https://user-images.githubusercontent.com/105309579/183776818-50cfd748-1ca1-4a4e-b5c6-838b4ae144e3.png)
![Screenshot_20220809-235958](https://user-images.githubusercontent.com/105309579/183776849-e576442c-7c42-4a33-885a-aaac402de27e.png)

**Comment by Osayomwanbo** [comment]
Done

**Comment by danielpeace7** [comment]
Well done
