### ISSUE TITLE
PROVIDE CONTENTS IN LANDING PAGE AND DESIGN

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#46]
Kindly submit the figma link and screenshot of the design

**Comment by Crystannson** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=242%3A27
![Landing page](https://user-images.githubusercontent.com/53399623/183855095-a2514c6e-8f83-46d0-bebd-4141c1de9ea2.png)
1

**Comment by Crystannson** [comment]
Done

**Comment by danielpeace7** [comment]
Well done
