### ISSUE TITLE
DEVELOP PROTOTYPE FOR MOBILE VIEW OF THE DESIGN PROJECT

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#47]
Kindly submit the figma link and screenshot of the design. Thanks

**Comment by Crystannson** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=242%3A27
![Landing page](https://user-images.githubusercontent.com/53399623/183854662-aae71b41-0687-45bc-b76d-8e3cb0f96523.png)
1

**Comment by Crystannson** [comment]
Done

**Comment by Crystannson** [comment]
https://www.figma.com/file/M72dHcHNJItdlvUDyYeva7/METADATA-D?node-id=242%3A271
![Prototype of mobile](https://user-images.githubusercontent.com/53399623/183872123-a08ee395-ce1a-42c8-831f-8f32dcf70ede.jpeg)

**Comment by danielpeace7** [comment]
Well done
