### ISSUE TITLE
CREATE SAVED PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#7]

**Comment by danielpeace7** [comment]
Please create the saved page of the design and attach the link to your repo here

**Comment by BunmiFash** [comment]
https://github.com/BunmiFash/Metadata
![Screenshot (11)](https://user-images.githubusercontent.com/49479039/183667314-a7666dfa-2106-4810-9c9a-6b69f0a6899a.png)

**Comment by danielpeace7** [comment]
Well done
