### ISSUE TITLE
CREATE FINAL PAGE

### ISSUE THREAD

**Issue by danielpeace7** [zuri-training/Fetch_Metadata_Team82#8]
Please create the final page of the design and attach the link to your repo here

**Comment by Prissy-Ama** [comment]
I worked on the desktop and mobile view of the homepage of the fetch_metadata website. This is the link to the repo:
https://github.com/Prissy-Ama/frontend_metadata_display_page

**Comment by Prissy-Ama** [comment]
![20220809_222545](https://user-images.githubusercontent.com/102432671/183765606-444f40a4-07b6-4e45-a76b-43048de823db.jpg)

**Comment by danielpeace7** [comment]
Well done
